package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const changelogHeader = "# Changelog\n\nAll notable changes to this automations repository are documented here. This file is auto-generated by `qui-sync export`; entries are prepended on each export that produces a diff.\n"

// AppendChangelog prepends a new dated section to CHANGELOG.md describing the diff.
// Existing contents are preserved. If CHANGELOG_NOTES.md exists, the notes under
// the current date heading are merged into the generated section.
func AppendChangelog(repoDir string, diff *ExportDiff, when time.Time) error {
	path := filepath.Join(repoDir, "CHANGELOG.md")
	date := when.Format("2006-01-02")

	section := renderSection(date, diff, readManualNotes(repoDir, date))

	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		content := changelogHeader + "\n" + section
		return os.WriteFile(path, []byte(content), 0o644)
	}
	if err != nil {
		return err
	}

	// Split existing: header (up to first "## " or end of header block) + rest.
	header, rest := splitHeader(string(existing))
	content := header + section + rest
	return os.WriteFile(path, []byte(content), 0o644)
}

// splitHeader returns (header, rest) where header is everything up to (but not
// including) the first "## " line, and rest is the remainder. If no section
// heading is found, the whole file is treated as header.
func splitHeader(s string) (string, string) {
	lines := strings.SplitAfter(s, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "## ") {
			return strings.Join(lines[:i], ""), strings.Join(lines[i:], "")
		}
	}
	// No existing section — ensure header ends with blank line before we append.
	if !strings.HasSuffix(s, "\n\n") {
		if strings.HasSuffix(s, "\n") {
			s += "\n"
		} else {
			s += "\n\n"
		}
	}
	return s, ""
}

func renderSection(date string, diff *ExportDiff, manualNotes string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## %s\n\n", date)

	if manualNotes != "" {
		sb.WriteString(strings.TrimRight(manualNotes, "\n"))
		sb.WriteString("\n\n")
	}

	if len(diff.Added) > 0 {
		sb.WriteString("### Added\n")
		for _, e := range diff.Added {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s\n", e.Slug, e.Category, e.Name)
		}
		sb.WriteString("\n")
	}
	if len(diff.Updated) > 0 {
		sb.WriteString("### Updated\n")
		for _, e := range diff.Updated {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s\n", e.Slug, e.Category, e.Name)
		}
		sb.WriteString("\n")
	}
	if len(diff.Renamed) > 0 {
		sb.WriteString("### Renamed\n")
		for _, e := range diff.Renamed {
			fmt.Fprintf(&sb, "- `%s` (%s) — \"%s\" → \"%s\"\n", e.Slug, e.Category, e.OldName, e.Name)
		}
		sb.WriteString("\n")
	}
	if len(diff.Removed) > 0 {
		sb.WriteString("### Removed\n")
		for _, e := range diff.Removed {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s (archived to `backup/`)\n", e.Slug, e.Category, e.Name)
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// readManualNotes looks in CHANGELOG_NOTES.md for a section matching the date.
// Format: each section starts with "## YYYY-MM-DD" and contains free-form markdown.
// The matching section is returned without its heading. Any trailing newlines are trimmed.
func readManualNotes(repoDir, date string) string {
	path := filepath.Join(repoDir, "CHANGELOG_NOTES.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	heading := "## " + date
	lines := strings.Split(string(data), "\n")
	inSection := false
	var out []string
	for _, l := range lines {
		if strings.HasPrefix(l, "## ") {
			if inSection {
				break
			}
			if strings.TrimSpace(l) == heading {
				inSection = true
				continue
			}
		}
		if inSection {
			out = append(out, l)
		}
	}
	return strings.TrimSpace(strings.Join(out, "\n"))
}

// WriteChangelogNote upserts a dated section in CHANGELOG_NOTES.md.
//
// If note is empty, the section for that date is removed. Otherwise the
// section is replaced (if it already exists) or prepended as a new
// top-of-file section, matching the ordering convention CHANGELOG.md
// uses (newest date first).
//
// The file is user-visible and can be hand-edited alongside the
// generated CHANGELOG.md. readManualNotes picks up the content during
// the next export's AppendChangelog run.
func WriteChangelogNote(repoDir, date, note string) error {
	path := filepath.Join(repoDir, "CHANGELOG_NOTES.md")
	note = strings.TrimSpace(note)

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	// Split the existing file into sections keyed by heading line.
	// Anything before the first "## " is preamble (usually blank).
	preamble, sections := splitNotes(string(existing))
	heading := "## " + date

	// Remove any existing section for this date.
	filtered := sections[:0]
	for _, s := range sections {
		if strings.TrimSpace(strings.SplitN(s, "\n", 2)[0]) != heading {
			filtered = append(filtered, s)
		}
	}
	sections = filtered

	// Prepend the new section (if non-empty) so the most recent date is
	// at the top — matches the ordering CHANGELOG.md follows.
	if note != "" {
		newSection := heading + "\n\n" + note + "\n"
		sections = append([]string{newSection}, sections...)
	}

	if len(sections) == 0 && strings.TrimSpace(preamble) == "" {
		// Nothing left to write — remove the file if it exists, silent
		// no-op if it doesn't.
		_ = os.Remove(path)
		return nil
	}

	var out strings.Builder
	if preamble != "" {
		out.WriteString(preamble)
	}
	for i, s := range sections {
		if i > 0 && !strings.HasSuffix(out.String(), "\n\n") {
			out.WriteString("\n")
		}
		out.WriteString(s)
	}
	return os.WriteFile(path, []byte(out.String()), 0o644)
}

// splitNotes divides CHANGELOG_NOTES.md into (preamble, sections) where
// preamble is everything before the first "## " heading, and sections
// is a slice of section strings each beginning with their heading line.
func splitNotes(s string) (preamble string, sections []string) {
	lines := strings.SplitAfter(s, "\n")
	var cur strings.Builder
	inSection := false
	for _, l := range lines {
		if strings.HasPrefix(l, "## ") {
			if inSection {
				sections = append(sections, cur.String())
				cur.Reset()
			} else {
				preamble = cur.String()
				cur.Reset()
				inSection = true
			}
		}
		cur.WriteString(l)
	}
	if cur.Len() > 0 {
		if inSection {
			sections = append(sections, cur.String())
		} else {
			preamble = cur.String()
		}
	}
	return preamble, sections
}
