package core

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const changelogHeader = "# Changelog\n\nAll notable changes to this automations repository are documented here. This file is auto-generated by `qui-sync export`; entries are prepended on each export that produces a diff.\n"

// AppendChangelog writes today's export section to CHANGELOG.md.
//
// If the existing top section is for the same date, the fresh section
// is MERGED into it rather than replacing it wholesale — earlier
// commits on the same day stay visible in CHANGELOG.md, with later
// commits' entries upserted by slug. This matters since v0.4.1: with
// per-rule include filters the second Commit of a day can include only
// a tiny subset of rules, and the old "replace" behaviour was losing
// the morning's entries from the file. Git history of CHANGELOG.md
// still retains every prior state, so nothing is irrecoverably lost
// either way — this just makes the working copy reflect "everything I
// pushed today" instead of "only the last batch I pushed today".
//
// Merge semantics:
//   - Bullets are keyed by (group, slug). Same-slug entries: later wins
//     (the new bullet replaces the old one, including its comment).
//     Different-slug entries are added to the group.
//   - Groups present in the existing section survive even when the fresh
//     diff has nothing in them.
//   - The global note: a fresh non-empty note replaces the existing one;
//     an empty fresh note preserves whatever the existing section had.
//   - Bullets the parser can't decode (hand-edited / unusual format)
//     are preserved verbatim, anchored by their original position.
//
// note is the free-form markdown the maintainer typed into the Export
// panel (empty string = no note paragraph).
func AppendChangelog(repoDir string, diff *ExportDiff, when time.Time, note string) error {
	// One-shot migration: earlier qui-sync versions wrote notes into a
	// separate CHANGELOG_NOTES.md and merged them at export time. The
	// single-file model makes that file dead weight; remove it if it's
	// hanging around so `git add -A` stages the deletion alongside the
	// next export commit. Failure is non-fatal — worst case it sits on
	// disk for another day.
	_ = os.Remove(filepath.Join(repoDir, "CHANGELOG_NOTES.md"))

	path := filepath.Join(repoDir, "CHANGELOG.md")
	date := when.Format("2006-01-02")
	section := renderSection(date, diff, strings.TrimSpace(note))

	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return os.WriteFile(path, []byte(changelogHeader+"\n"+section), 0o644)
	}
	if err != nil {
		return err
	}

	header, rest := splitHeader(string(existing))
	if existingTop, remainder, found := peelTopSectionForDate(rest, date); found {
		section = mergeSameDaySections(existingTop, section)
		rest = remainder
	}
	return os.WriteFile(path, []byte(header+section+rest), 0o644)
}

// UpdateLatestExportNote rewrites the note paragraph of the top
// (most-recent) section in CHANGELOG.md. The generated group lists
// (Added/Updated/Renamed/Archived) are preserved byte-for-byte.
//
// An empty note removes any existing note paragraph. Returns an error
// if CHANGELOG.md has no section yet — an edit needs an existing entry
// to attach to.
func UpdateLatestExportNote(repoDir, note string) error {
	path := filepath.Join(repoDir, "CHANGELOG.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	header, rest := splitHeader(string(data))
	if !strings.HasPrefix(rest, "## ") {
		return fmt.Errorf("no changelog sections yet — run an export first")
	}
	top, tail := sliceFirstSection(rest)
	updated := replaceNoteInSection(top, strings.TrimSpace(note))
	return os.WriteFile(path, []byte(header+updated+tail), 0o644)
}

// CurrentExportNote returns the note paragraph of the top section in
// CHANGELOG.md, or "" if no note / no sections / no file. Used by the
// UI to pre-fill the Edit-note textarea.
func CurrentExportNote(repoDir string) (string, error) {
	path := filepath.Join(repoDir, "CHANGELOG.md")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	_, rest := splitHeader(string(data))
	if !strings.HasPrefix(rest, "## ") {
		return "", nil
	}
	top, _ := sliceFirstSection(rest)
	return extractNoteFromSection(top), nil
}

// splitHeader returns (header, rest) where header is everything up to
// (but not including) the first "## " line, and rest is the remainder.
// If no section heading is found, the whole file is treated as header.
func splitHeader(s string) (string, string) {
	lines := strings.SplitAfter(s, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "## ") {
			return strings.Join(lines[:i], ""), strings.Join(lines[i:], "")
		}
	}
	if !strings.HasSuffix(s, "\n\n") {
		if strings.HasSuffix(s, "\n") {
			s += "\n"
		} else {
			s += "\n\n"
		}
	}
	return s, ""
}

// sliceFirstSection returns (section, rest). section includes the
// leading "## " heading and runs up to (but not including) the next
// "## " heading at line start. s MUST begin with "## ".
func sliceFirstSection(s string) (section, rest string) {
	lines := strings.SplitAfter(s, "\n")
	for i, l := range lines {
		if i > 0 && strings.HasPrefix(l, "## ") {
			return strings.Join(lines[:i], ""), strings.Join(lines[i:], "")
		}
	}
	return s, ""
}

// peelTopSectionForDate checks whether the top section of rest is for
// the given date. Heading is matched by prefix so hand-edited suffixes
// like "## 2026-04-19 (release)" still count as the same day.
func peelTopSectionForDate(rest, date string) (section, remainder string, found bool) {
	if !strings.HasPrefix(rest, "## ") {
		return "", rest, false
	}
	eol := strings.Index(rest, "\n")
	heading := rest
	if eol >= 0 {
		heading = rest[:eol]
	}
	prefix := "## " + date
	trimmed := strings.TrimSpace(heading)
	if trimmed != prefix && !strings.HasPrefix(trimmed, prefix+" ") {
		return "", rest, false
	}
	section, remainder = sliceFirstSection(rest)
	return section, remainder, true
}

// extractNoteFromSection returns the note paragraph of a section, or ""
// if none. Section shape: "## DATE\n\n[note\n\n][### Group\n...]..."
func extractNoteFromSection(section string) string {
	after := stripHeadingPrefix(section)
	if strings.HasPrefix(after, "### ") {
		return ""
	}
	if i := strings.Index(after, "\n### "); i >= 0 {
		return strings.TrimSpace(after[:i])
	}
	return strings.TrimSpace(after)
}

// replaceNoteInSection rewrites a section's note paragraph, preserving
// heading and group lists. Empty note drops the note paragraph.
func replaceNoteInSection(section, note string) string {
	after := stripHeadingPrefix(section)
	headingLen := len(section) - len(after)
	heading := section[:headingLen]

	var groups string
	switch {
	case strings.HasPrefix(after, "### "):
		groups = after
	default:
		if i := strings.Index(after, "\n### "); i >= 0 {
			groups = after[i+1:]
		}
	}

	if note == "" {
		return heading + groups
	}
	return heading + note + "\n\n" + groups
}

// stripHeadingPrefix returns the content after "## DATE\n" plus one
// optional blank line. If s is empty or malformed, returns "".
func stripHeadingPrefix(s string) string {
	i := strings.Index(s, "\n")
	if i < 0 {
		return ""
	}
	rest := s[i+1:]
	if strings.HasPrefix(rest, "\n") {
		rest = rest[1:]
	}
	return rest
}

func renderSection(date string, diff *ExportDiff, manualNote string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## %s\n\n", date)

	if manualNote != "" {
		sb.WriteString(strings.TrimRight(manualNote, "\n"))
		sb.WriteString("\n\n")
	}

	if len(diff.Added) > 0 {
		sb.WriteString("### Added\n")
		for _, e := range diff.Added {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s", e.Slug, e.Category, e.Name)
			writeCommentSuffix(&sb, e.Comment)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}
	if len(diff.Updated) > 0 {
		sb.WriteString("### Updated\n")
		for _, e := range diff.Updated {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s", e.Slug, e.Category, e.Name)
			writeCommentSuffix(&sb, e.Comment)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}
	if len(diff.Renamed) > 0 {
		sb.WriteString("### Renamed\n")
		for _, e := range diff.Renamed {
			fmt.Fprintf(&sb, "- `%s` (%s) — \"%s\" → \"%s\"", e.Slug, e.Category, e.OldName, e.Name)
			writeCommentSuffix(&sb, e.Comment)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}
	if len(diff.Removed) > 0 {
		sb.WriteString("### Archived\n")
		for _, e := range diff.Removed {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s (moved to `archive/%s/`)", e.Slug, e.Category, e.Name, e.Category)
			writeCommentSuffix(&sb, e.Comment)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// writeCommentSuffix appends " — *<comment>*" when comment is non-empty.
// Single-line only — newlines are collapsed to spaces so a multi-line
// comment cannot break the markdown bullet structure. Asterisks inside
// the comment are escaped because the suffix renders the comment as
// italic markdown — an unescaped `*` would close the italic span early
// and produce broken output.
func writeCommentSuffix(sb *strings.Builder, comment string) {
	c := strings.TrimSpace(comment)
	if c == "" {
		return
	}
	c = strings.ReplaceAll(c, "\r\n", " ")
	c = strings.ReplaceAll(c, "\n", " ")
	c = strings.ReplaceAll(c, "*", `\*`)
	fmt.Fprintf(sb, " — *%s*", c)
}

// --- same-day merge ----------------------------------------------------
//
// parsedSection is the structured form of one "## DATE" block. The
// merge layer parses both the existing top section and the fresh
// freshly-rendered section into this shape, upserts fresh into
// existing, then renders the merged result back to markdown.
//
// "groupOrder" preserves the section order as it was encountered (or
// canonical order for fresh sections). New groups added by a fresh
// commit get appended after existing groups so the user's visual
// ordering on disk stays stable as much as possible.

type parsedBullet struct {
	// slug is the key inside the first backticks of a "- `slug` ..."
	// line. Empty when the bullet cannot be parsed — in that case the
	// raw line is preserved verbatim and excluded from upsert matching.
	slug string
	// line is the bullet's full text, including the leading "- "
	// marker and any trailing comment suffix, no newline.
	line string
}

type parsedGroup struct {
	heading string // e.g. "### Added"
	// bullets retains insertion order. We don't dedupe by slug here —
	// merge does that step explicitly so the ordering is deterministic.
	bullets []parsedBullet
}

type parsedSection struct {
	heading    string // first line, e.g. "## 2026-05-17" or "## 2026-05-17 (release)"
	note       string // free-form paragraph between heading and first ### group, trimmed
	groups     []parsedGroup
	groupIndex map[string]int // heading -> index into groups
}

// bulletRe captures the slug between the first pair of backticks on a
// "- " line. Hand-edited bullets that don't follow this exact shape
// get preserved verbatim with slug=="".
var bulletRe = regexp.MustCompile("^- `([^`]+)`")

// parseSection breaks a "## DATE\n..." block into structured form so
// it can be merged with a freshly rendered section. The input must
// begin with "## ". An empty or malformed input returns a section
// with the original text stuck in heading — caller should fall back
// to "replace" in that case (mergeSameDaySections handles it).
func parseSection(s string) parsedSection {
	out := parsedSection{groupIndex: map[string]int{}}
	if !strings.HasPrefix(s, "## ") {
		return out
	}
	eol := strings.Index(s, "\n")
	if eol < 0 {
		out.heading = strings.TrimRight(s, "\n")
		return out
	}
	out.heading = strings.TrimRight(s[:eol], "\n")
	rest := s[eol+1:]

	// Drop one optional blank line after the heading.
	if strings.HasPrefix(rest, "\n") {
		rest = rest[1:]
	}

	// Note paragraph: everything up to the first "### " line (or end of
	// section). Could be empty.
	var groupsPart string
	if strings.HasPrefix(rest, "### ") {
		out.note = ""
		groupsPart = rest
	} else if i := strings.Index(rest, "\n### "); i >= 0 {
		out.note = strings.TrimSpace(rest[:i])
		groupsPart = rest[i+1:]
	} else {
		out.note = strings.TrimSpace(rest)
		groupsPart = ""
	}

	// Now split groupsPart into "### Heading\n<bullets>\n" chunks.
	lines := strings.Split(groupsPart, "\n")
	var current *parsedGroup
	for _, line := range lines {
		if strings.HasPrefix(line, "### ") {
			out.groups = append(out.groups, parsedGroup{heading: strings.TrimRight(line, "\r")})
			current = &out.groups[len(out.groups)-1]
			out.groupIndex[current.heading] = len(out.groups) - 1
			continue
		}
		if current == nil {
			continue
		}
		if strings.TrimSpace(line) == "" {
			continue
		}
		if !strings.HasPrefix(line, "- ") {
			// Continuation or weirdness — attach to the previous
			// bullet if one exists, otherwise drop. Keeps multi-line
			// hand-edits associated with their bullet.
			if len(current.bullets) > 0 {
				current.bullets[len(current.bullets)-1].line += "\n" + line
			}
			continue
		}
		b := parsedBullet{line: line}
		if m := bulletRe.FindStringSubmatch(line); len(m) == 2 {
			b.slug = m[1]
		}
		current.bullets = append(current.bullets, b)
	}
	return out
}

// mergeSameDaySections merges a fresh section into an existing one for
// the same date. Returns the merged section as a markdown string with a
// single trailing blank line — same shape as renderSection's output.
//
// If parsing fails outright (existing isn't a recognisable section),
// the fresh section is returned unchanged, matching the pre-merge
// "replace" behaviour as a safe fallback.
func mergeSameDaySections(existing, fresh string) string {
	e := parseSection(existing)
	f := parseSection(fresh)
	if e.heading == "" {
		return fresh
	}

	merged := parsedSection{
		heading:    e.heading, // preserve any user suffix on the date line
		groupIndex: map[string]int{},
	}

	// Note merge: fresh non-empty wins, else keep existing.
	if f.note != "" {
		merged.note = f.note
	} else {
		merged.note = e.note
	}

	// Copy existing groups (with their bullets) into merged so order is
	// preserved. We then upsert fresh entries on top.
	for _, g := range e.groups {
		merged.groups = append(merged.groups, parsedGroup{
			heading: g.heading,
			bullets: append([]parsedBullet(nil), g.bullets...),
		})
		merged.groupIndex[g.heading] = len(merged.groups) - 1
	}

	// Upsert fresh entries.
	for _, fg := range f.groups {
		idx, ok := merged.groupIndex[fg.heading]
		if !ok {
			merged.groups = append(merged.groups, parsedGroup{heading: fg.heading})
			idx = len(merged.groups) - 1
			merged.groupIndex[fg.heading] = idx
		}
		target := &merged.groups[idx]
		for _, fb := range fg.bullets {
			if fb.slug == "" {
				// Unparseable bullet from the fresh side — just append.
				// Should be rare since renderSection's output is always
				// parseable.
				target.bullets = append(target.bullets, fb)
				continue
			}
			replaced := false
			for i := range target.bullets {
				if target.bullets[i].slug == fb.slug {
					target.bullets[i] = fb // later wins
					replaced = true
					break
				}
			}
			if !replaced {
				target.bullets = append(target.bullets, fb)
			}
		}
	}

	return renderParsedSection(merged)
}

// renderParsedSection writes a parsedSection back as markdown. The
// output ends with a trailing blank line so it concatenates cleanly
// with whatever follows in the file.
func renderParsedSection(p parsedSection) string {
	var sb strings.Builder
	sb.WriteString(p.heading)
	sb.WriteString("\n\n")
	if p.note != "" {
		sb.WriteString(p.note)
		sb.WriteString("\n\n")
	}
	for _, g := range p.groups {
		if len(g.bullets) == 0 {
			continue
		}
		sb.WriteString(g.heading)
		sb.WriteString("\n")
		for _, b := range g.bullets {
			sb.WriteString(b.line)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}
	return sb.String()
}
