package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const changelogHeader = "# Changelog\n\nAll notable changes to this automations repository are documented here. This file is auto-generated by `qui-sync export`; entries are prepended on each export that produces a diff.\n"

// AppendChangelog writes today's export section to CHANGELOG.md.
//
// If the existing top section is for the same date, it is REPLACED
// rather than a duplicate prepended — re-running export on the same
// day should collapse to a single up-to-date entry.
//
// note is the free-form markdown the maintainer typed into the Export
// panel (empty string = no note paragraph).
func AppendChangelog(repoDir string, diff *ExportDiff, when time.Time, note string) error {
	// One-shot migration: earlier qui-sync versions wrote notes into a
	// separate CHANGELOG_NOTES.md and merged them at export time. The
	// single-file model makes that file dead weight; remove it if it's
	// hanging around so `git add -A` stages the deletion alongside the
	// next export commit. Failure is non-fatal — worst case it sits on
	// disk for another day.
	_ = os.Remove(filepath.Join(repoDir, "CHANGELOG_NOTES.md"))

	path := filepath.Join(repoDir, "CHANGELOG.md")
	date := when.Format("2006-01-02")
	section := renderSection(date, diff, strings.TrimSpace(note))

	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return os.WriteFile(path, []byte(changelogHeader+"\n"+section), 0o644)
	}
	if err != nil {
		return err
	}

	header, rest := splitHeader(string(existing))
	if _, remainder, found := peelTopSectionForDate(rest, date); found {
		rest = remainder
	}
	return os.WriteFile(path, []byte(header+section+rest), 0o644)
}

// UpdateLatestExportNote rewrites the note paragraph of the top
// (most-recent) section in CHANGELOG.md. The generated group lists
// (Added/Updated/Renamed/Archived) are preserved byte-for-byte.
//
// An empty note removes any existing note paragraph. Returns an error
// if CHANGELOG.md has no section yet — an edit needs an existing entry
// to attach to.
func UpdateLatestExportNote(repoDir, note string) error {
	path := filepath.Join(repoDir, "CHANGELOG.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	header, rest := splitHeader(string(data))
	if !strings.HasPrefix(rest, "## ") {
		return fmt.Errorf("no changelog sections yet — run an export first")
	}
	top, tail := sliceFirstSection(rest)
	updated := replaceNoteInSection(top, strings.TrimSpace(note))
	return os.WriteFile(path, []byte(header+updated+tail), 0o644)
}

// CurrentExportNote returns the note paragraph of the top section in
// CHANGELOG.md, or "" if no note / no sections / no file. Used by the
// UI to pre-fill the Edit-note textarea.
func CurrentExportNote(repoDir string) (string, error) {
	path := filepath.Join(repoDir, "CHANGELOG.md")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	_, rest := splitHeader(string(data))
	if !strings.HasPrefix(rest, "## ") {
		return "", nil
	}
	top, _ := sliceFirstSection(rest)
	return extractNoteFromSection(top), nil
}

// splitHeader returns (header, rest) where header is everything up to
// (but not including) the first "## " line, and rest is the remainder.
// If no section heading is found, the whole file is treated as header.
func splitHeader(s string) (string, string) {
	lines := strings.SplitAfter(s, "\n")
	for i, l := range lines {
		if strings.HasPrefix(l, "## ") {
			return strings.Join(lines[:i], ""), strings.Join(lines[i:], "")
		}
	}
	if !strings.HasSuffix(s, "\n\n") {
		if strings.HasSuffix(s, "\n") {
			s += "\n"
		} else {
			s += "\n\n"
		}
	}
	return s, ""
}

// sliceFirstSection returns (section, rest). section includes the
// leading "## " heading and runs up to (but not including) the next
// "## " heading at line start. s MUST begin with "## ".
func sliceFirstSection(s string) (section, rest string) {
	lines := strings.SplitAfter(s, "\n")
	for i, l := range lines {
		if i > 0 && strings.HasPrefix(l, "## ") {
			return strings.Join(lines[:i], ""), strings.Join(lines[i:], "")
		}
	}
	return s, ""
}

// peelTopSectionForDate checks whether the top section of rest is for
// the given date. Heading is matched by prefix so hand-edited suffixes
// like "## 2026-04-19 (release)" still count as the same day.
func peelTopSectionForDate(rest, date string) (section, remainder string, found bool) {
	if !strings.HasPrefix(rest, "## ") {
		return "", rest, false
	}
	eol := strings.Index(rest, "\n")
	heading := rest
	if eol >= 0 {
		heading = rest[:eol]
	}
	prefix := "## " + date
	trimmed := strings.TrimSpace(heading)
	if trimmed != prefix && !strings.HasPrefix(trimmed, prefix+" ") {
		return "", rest, false
	}
	section, remainder = sliceFirstSection(rest)
	return section, remainder, true
}

// extractNoteFromSection returns the note paragraph of a section, or ""
// if none. Section shape: "## DATE\n\n[note\n\n][### Group\n...]..."
func extractNoteFromSection(section string) string {
	after := stripHeadingPrefix(section)
	if strings.HasPrefix(after, "### ") {
		return ""
	}
	if i := strings.Index(after, "\n### "); i >= 0 {
		return strings.TrimSpace(after[:i])
	}
	return strings.TrimSpace(after)
}

// replaceNoteInSection rewrites a section's note paragraph, preserving
// heading and group lists. Empty note drops the note paragraph.
func replaceNoteInSection(section, note string) string {
	after := stripHeadingPrefix(section)
	headingLen := len(section) - len(after)
	heading := section[:headingLen]

	var groups string
	switch {
	case strings.HasPrefix(after, "### "):
		groups = after
	default:
		if i := strings.Index(after, "\n### "); i >= 0 {
			groups = after[i+1:]
		}
	}

	if note == "" {
		return heading + groups
	}
	return heading + note + "\n\n" + groups
}

// stripHeadingPrefix returns the content after "## DATE\n" plus one
// optional blank line. If s is empty or malformed, returns "".
func stripHeadingPrefix(s string) string {
	i := strings.Index(s, "\n")
	if i < 0 {
		return ""
	}
	rest := s[i+1:]
	if strings.HasPrefix(rest, "\n") {
		rest = rest[1:]
	}
	return rest
}

func renderSection(date string, diff *ExportDiff, manualNote string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "## %s\n\n", date)

	if manualNote != "" {
		sb.WriteString(strings.TrimRight(manualNote, "\n"))
		sb.WriteString("\n\n")
	}

	if len(diff.Added) > 0 {
		sb.WriteString("### Added\n")
		for _, e := range diff.Added {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s\n", e.Slug, e.Category, e.Name)
		}
		sb.WriteString("\n")
	}
	if len(diff.Updated) > 0 {
		sb.WriteString("### Updated\n")
		for _, e := range diff.Updated {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s\n", e.Slug, e.Category, e.Name)
		}
		sb.WriteString("\n")
	}
	if len(diff.Renamed) > 0 {
		sb.WriteString("### Renamed\n")
		for _, e := range diff.Renamed {
			fmt.Fprintf(&sb, "- `%s` (%s) — \"%s\" → \"%s\"\n", e.Slug, e.Category, e.OldName, e.Name)
		}
		sb.WriteString("\n")
	}
	if len(diff.Removed) > 0 {
		sb.WriteString("### Archived\n")
		for _, e := range diff.Removed {
			fmt.Fprintf(&sb, "- `%s` (%s) — %s (moved to `archive/%s/`)\n", e.Slug, e.Category, e.Name, e.Category)
		}
		sb.WriteString("\n")
	}

	return sb.String()
}
